### ISSUE TITLE
article 12215 v1 scrape error

### ISSUE THREAD

**Issue by lsh-0** [elifesciences/bot-lax-adaptor#316]
getting this attempting to re-generate a fixture for lax:

```
$ ./scrape-article.sh article-xml/articles/elife-12215-v1.xml 
ERROR - 2017-09-27 17:18:52,266 - failed to render doc 'https://raw.githubusercontent.com/elifesciences/elife-article-xml/f0dd69e8d0976e68868ced40de0b7140c040e250/articles/elife-12215-v1.xml' with error: ('Author missing required competingInterests', {'version': 1, 'msid': u'12215'}) -- {}
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/home/luke/dev/python/bot-lax-adaptor/src/conf.py", line 84, in format
    record.__dict__['extra'] = utils.json_dumps(unknown_fields)
  File "/home/luke/dev/python/bot-lax-adaptor/src/utils.py", line 121, in json_dumps
    return json.dumps(obj, default=datetime_handler, **kwargs)
  File "/usr/lib64/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/home/luke/dev/python/bot-lax-adaptor/src/utils.py", line 120, in datetime_handler
    raise TypeError('Object of type %s with value of %s is not JSON serializable' % (type(obj), repr(obj)))
TypeError: Object of type <type 'file'> with value of <open file 'article-xml/articles/elife-12215-v1.xml', mode 'r' at 0x7f7c0dad9390> is not JSON serializable
Logged from file main.py, line 659
Traceback (most recent call last):
  File "src/main.py", line 671, in <module>
    print main(doc, args)
  File "src/main.py", line 650, in main
    article_json = render_single(doc, **ctx)
  File "src/main.py", line 612, in render_single
    article_data = postprocess(render(description, [soup], ctx)[0], ctx)
  File "src/main.py", line 486, in postprocess
    partial(manual_overrides, ctx),
  File "/home/luke/dev/python/bot-lax-adaptor/venv/lib/python2.7/site-packages/et3/render.py", line 21, in doall
    item = do(item, seg, ctx)
  File "/home/luke/dev/python/bot-lax-adaptor/venv/lib/python2.7/site-packages/et3/render.py", line 13, in do
    return segment(item)
  File "src/main.py", line 428, in check_authors
    raise ValueError("Author missing required competingInterests", context)
ValueError: ('Author missing required competingInterests', {'version': 1, 'msid': u'12215'})
```

this is using the latest `asset-file-label-title-testing-validation` branch, latest article-xml.

haven't investigated yet, but I remember @gnott mentioning doing a complete scrape and not finding any errors.

**Comment by lsh-0** [comment]
I'll ping @giorgiosironi  as well.

I've been able to almost finish my work on lax thanks to your work in this branch. I just need to regenerate the test fixture so they're on api v2. then I'll be happy. happier.

**Comment by giorgiosironi** [comment]
```
TypeError: Object of type <type 'file'> with value of <open file 'article-xml/articles/elife-12215-v1.xml', mode 'r' at 0x7f7c0dad9390> is not JSON serializable
```
seems a problem in logging but passing a file in some of the extra parameters. To be resolved, but shouldn't affect the JSON generation.

```
ValueError: ('Author missing required competingInterests', {'version': 1, 'msid': u'12215'})
```
is a schema validation error - which version of api-raml are you getting? Is it the same as the PR on api-raml? Has its `dist` been recompiled with `node compile.js` which is a manual step to be done on branches?

**Comment by gnott** [comment]
I think I got a validation error on author competingInterests before too, and it turned out the file was missing or empty.

I already pre-compiled the schema dist files in the branch of the API RAML schema used in my test branch, so it should't be required I think to recompile. 

I suggest to do a full ``pip uninstall elifetools`` and a ``pip install -r requirements.txt`` again (or the equivalent shell script). Check the``elife-12215-v1.xml`` file exists where you expect it to be. Also make sure you've run a ``download-api-raml.sh`` for sure, but I don't think it got as far as validating anything, the output is possibly blank or the XML file was not found (I think).

**Comment by lsh-0** [comment]
thanks guys, I'll dig a little today

**Comment by lsh-0** [comment]
ok, two fixes. the first one is trivial and was simply an object being passed to the logger that couldn't be serialized. 

in the second one I've simply disabled  the `check_authors` code with the intent to remove it entirely: https://github.com/elifesciences/bot-lax-adaptor/blob/26df0e7416e5a53a14fdd7361a462be90aa2050f/src/main.py#L414-L435

The case appears to be: if the author is a group of authors, and no competing interests have been declared, fail with a ValueError. 

I think this sort of logic belongs in the article schema. Pinging @thewilkybarkid to see if it's covered or not.

**Comment by thewilkybarkid** [comment]
It can't be since it's not always true. (We don't have a schema per article type.)

**Comment by lsh-0** [comment]
> It can't be since it's not always true. (We don't have a schema per article type.)

this is an interesting state we find ourselves in then. there are checks we could be doing (like the above) but can't because we have to use the common set of features between all articles. I suppose it should be covered in the schematron tests then.

I can't replicate the failure this morning after updating the article-xml repo. Taking a look at the install scripts, `download-elife-xml.sh` isn't actually called anywhere, so I could have had a very old version hanging around.

that aside, I don't think that place in the code is where additional checks to the schema validation should happen, if they should be happening at all. If there is a real need for them, we can put it in `validate.py`. I'll ask Melissa what the process is for adding new rules to schematron
