### ISSUE TITLE
ISBN validation failure: `TypeError: 'NoneType' object is not iterable`

### ISSUE THREAD

**Issue by seanwiseman** [elifesciences/bot-lax-adaptor#457]
Need to extend the changes made in [this commit](https://github.com/elifesciences/bot-lax-adaptor/commit/09e6ef12279867eb1229ba7a586a50f74df64868) to handle invalid string values as well as `None` values.

We have had a case in production where a long string value was given instead of a valid `isbn` which resulted in the below trace: (though this took some debugging, all we initially saw was `'NoneType' object is not iterable`
```
File: ...isbnlib/_ext.py", line 20, in mask
    return msk(isbn, separator)
 File: ...isbnlib/_msk.py", line 25, in msk
    ib = canonical(isbn)
File: ...isbnlib/_core.py", line 143, in canonical
    numb = [c for c in isbnlike if c in '0123456789Xx']
TypeError: 'NoneType' object is not iterable
```
Pinging @lsh-0

**Comment by lsh-0** [comment]
do we have an example of this string?

**Comment by seanwiseman** [comment]
Sure. This is how it was in the data: 

```
<pub-id pub-id-type="isbn">Microgenesis of perception: Conceptual, psychophysical, neurobiological </pub-id>
```
