### ISSUE TITLE
to_volume review for PoA

### ISSUE THREAD

**Issue by gnott** [elifesciences/bot-lax-adaptor#9]
Making a note while I merge conficts,

I think the logic on to_volume() for PoA may need to be reviewed. Volume should be calculated based on the PoA article's pub date year, and not from today's year.

**Comment by lsh-0** [comment]
yes! bot-lax has the ability to do it both ways (cc @giorgiosironi ) but we were being consistent with the EIF generation. has the time come to do the volume calculation properly?

**Comment by giorgiosironi** [comment]
Volume is ignored in the new URLs, so even if there is a slight change in POA articles that are reingested, it should be pretty stable. Needs to be done carefully, but it should be done.

**Comment by lsh-0** [comment]
I'll open a PR today for it

**Comment by lsh-0** [comment]
PR here: https://github.com/elifesciences/bot-lax-adaptor/pull/130

> Needs to be done carefully, but it should be done.

feel free to merge when you're confident
